version: '4'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1  # Use the service name 'redis' as the hostname

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:8000  # Use the service name 'backend' as the hostname

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
