# Generated by Django 4.2.9 on 2024-01-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceAlignmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=200)),
                ('alignments', models.CharField(max_length=1000)),
            ],
        ),
    ]
