# Generated by Django 4.2.9 on 2024-01-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_alignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencealignmentresult',
            name='query_number',
            field=models.CharField(default='some_default_value', max_length=16),
        ),
    ]
