# Generated by Django 4.2.9 on 2024-02-03 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dna_alignment', '0003_alter_sequencealignmentresult_alignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencealignmentresult',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
