# Generated by Django 4.2.9 on 2024-02-04 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dna_alignment', '0004_sequencealignmentresult_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencealignmentresult',
            name='id',
        ),
        migrations.AddField(
            model_name='sequencealignmentresult',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sequencealignmentresult',
            name='query_number',
            field=models.CharField(default='some_default_value', max_length=16, primary_key=True, serialize=False),
        ),
    ]
