# Generated by Django 4.2.9 on 2024-02-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_alignment', '0005_remove_sequencealignmentresult_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencealignmentresult',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
